version: '3.8'

services:
  echovault-mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: echovault-mcp-server
    environment:
      # EchoVault Configuration
      - USE_ECHOVAULT=true
      
      # Database Configuration
      - NEON_DSN=${NEON_DSN:-}
      - NEON_POOL_SIZE=5
      
      # Vector Search Configuration  
      - USE_QDRANT=true
      - QDRANT_URL=${QDRANT_URL:-}
      - QDRANT_API_KEY=${QDRANT_API_KEY:-}
      
      # Blob Storage Configuration
      - R2_ENDPOINT=${R2_ENDPOINT:-}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID:-}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY:-}
      - R2_BUCKET=${R2_BUCKET:-echovault-events}
      
      # Observability Configuration
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-}
      - PROMETHEUS_METRICS=true
      
      # Security Configuration
      - JWT_SECRET=${JWT_SECRET:-}
      
      # Memory Configuration
      - BLOB_THRESHOLD=32768
      - SUMMARY_THRESHOLD_DAYS=30
      - RETENTION_DAYS=365
      
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      
    restart: unless-stopped
    
    # MCP servers typically use stdio, so no ports exposed by default
    # Uncomment if you need HTTP access for debugging
    # ports:
    #   - "8000:8000"
    
    healthcheck:
      test: ["CMD", "python", "-c", "import src.mcp_memory_service.mcp_server; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    networks:
      - echovault-network

networks:
  echovault-network:
    driver: bridge

volumes:
  echovault-data:
    driver: local
  echovault-logs:
    driver: local 